/**
 * VisualizationGenerator facade class.
 * Delegates HTML and TUI rendering to specialized modules.
 */

import type { LogEntry, TimePhase } from "../workspace";
import type { BudgetData } from "./types";
import { PHASES, PHASE_MAP } from "./types";
import { HTML_STYLES } from "./styles";
import { buildSvgTimeline, buildEventList, formatDuration } from "./html-utils";
import { generateTUIView } from "./tui-gen";

export class VisualizationGenerator {
  /**
   * Generate a self-contained HTML report with inline SVG timeline.
   */
  generateHTML(
    trail: LogEntry[],
    currentPhase: TimePhase,
    budgetData: BudgetData,
    startTime: number,
  ): string {
    const { totalBudgetMs, elapsedMs, remainingMs } = budgetData;
    const progress = totalBudgetMs > 0 ? Math.min(elapsedMs / totalBudgetMs, 1) : 0;
    const progressPercent = Math.round(progress * 100);
    const remainingFormatted = formatDuration(remainingMs);
    const elapsedFormatted = formatDuration(elapsedMs);
    const totalFormatted = formatDuration(totalBudgetMs);

    const svgTimeline = buildSvgTimeline(trail, startTime, totalBudgetMs, progress);
    const eventList = buildEventList(trail, startTime, PHASE_MAP);

    const totalCalls = trail.length;
    const errors = trail.filter(t => t.isError).length;
    const validations = trail.filter(t => t.type === "validation").length;
    const passedValidations = trail.filter(t => t.passed).length;
    const toolCalls = trail.filter(t => t.type === "tool_call").length;

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>🍋 LemonHarness Execution Report</title>
<style>
${HTML_STYLES}
</style>
</head>
<body>
<div class="container">
  <h1>🍋 LemonHarness Execution Report</h1>
  <div class="subtitle">Generated at ${new Date().toISOString().replace("T", " ").slice(0, 19)}</div>

  <!-- Summary Cards -->
  <div class="summary">
    <div class="summary-card card-phase">
      <div class="label">Current Phase</div>
      <div class="value">${currentPhase.phase.toUpperCase()}</div>
      <div class="sub">${Math.round(currentPhase.phaseProgress * 100)}% through phase</div>
    </div>
    <div class="summary-card card-budget">
      <div class="label">Budget Used</div>
      <div class="value">${progressPercent}%</div>
      <div class="sub">${elapsedFormatted} / ${totalFormatted}</div>
    </div>
    <div class="summary-card card-calls">
      <div class="label">Tool Calls</div>
      <div class="value">${toolCalls}</div>
      <div class="sub">Across all phases</div>
    </div>
    <div class="summary-card card-errors">
      <div class="label">Errors</div>
      <div class="value" style="color: ${errors > 0 ? '#e74c3c' : '#27ae60'}">${errors}</div>
      <div class="sub">${totalCalls > 0 ? Math.round(errors / totalCalls * 100) : 0}% error rate</div>
    </div>
    <div class="summary-card card-validations">
      <div class="label">Validations</div>
      <div class="value">${validations}</div>
      <div class="sub">${passedValidations} passed, ${validations - passedValidations} failed</div>
    </div>
  </div>

  <!-- Budget Bar -->
  <div class="budget-section">
    <div class="budget-header">
      <span><strong>Budget Utilization</strong></span>
      <span>${elapsedFormatted} elapsed · ${remainingFormatted} remaining</span>
    </div>
    <div class="budget-bar">
      <div class="budget-fill" style="width: ${progressPercent}%"></div>
      <div class="label-overlay">${progressPercent}% used</div>
    </div>
    <div class="budget-markers">
      ${[0.3, 0.6, 0.9].map(r => `
        <div class="budget-marker" style="left: ${r * 100}%"></div>
      `).join("")}
    </div>
  </div>

  <!-- Timeline SVG -->
  <div class="timeline-section">
    <h2>🕐 Execution Timeline</h2>
    ${svgTimeline}
    <div class="legend">
      <div class="legend-item"><span class="legend-dot" style="background:#27ae60"></span> Tool call (success)</div>
      <div class="legend-item"><span class="legend-dot" style="background:#e74c3c"></span> Tool call (error)</div>
      <div class="legend-item"><span class="legend-diamond" style="background:#27ae60"></span> Validation (pass)</div>
      <div class="legend-item"><span class="legend-diamond" style="background:#e74c3c"></span> Validation (fail)</div>
      <div class="legend-item"><span style="display:inline-block;width:14px;height:4px;background:#ddd;border-radius:2px"></span> Phase boundary</div>
    </div>
  </div>

  <!-- Event List -->
  <div class="events-section">
    <h2>📋 Event Trail (${trail.length} entries)</h2>
    ${eventList}
  </div>

  <div class="footer">
    Generated by LemonHarness Visualization · <a href="#" onclick="window.print()">Print / Save PDF</a>
  </div>
</div>
</body>
</html>`;
  }

  /**
   * Generate a text-based ASCII visualization for the terminal.
   */
  generateTUI(
    trail: LogEntry[],
    currentPhase: TimePhase,
    budgetData: BudgetData,
    startTime: number,
  ): string {
    return generateTUIView(trail, currentPhase, budgetData, startTime);
  }
}
